### ISSUE TITLE
How to setup  in the Nearby function just 2 OR 3 layers in the dropdown menu?

### ISSUE THREAD

**Issue by GilbertLasnier** [BrianBunker/cmv-widgets#19]
I have almost 100 layers in the scroll box , where is the place to define the layers to make the Find Nearby function? That will be the best for the user...
Many thanks for your answer

**Comment by BrianBunker** [comment]
Hi GilbertLasnier, you'll want to modify this function in order to limit which layers are displayed in the drop-down (scroll box): https://github.com/BrianBunker/cmv-widgets/blob/master/Nearby/Nearby.js#L115-L136

**Comment by GilbertLasnier** [comment]
Merci I TRY…
