### ISSUE TITLE
Keep the point on the map

### ISSUE THREAD

**Issue by rkoch19** [BrianBunker/cmv-widgets#20]
Hello!

Is possible in your widget show the graphic point and keep it on the map? when I refresh the application the point desapear... is it possible? explaining ... I need to look for a coordinated and pin point then look for another coordinated and the previous point remains on the map ...only when I refresh the map the graphics, all the points desapear...

Thanks

Renato

**Comment by BrianBunker** [comment]
Hi @rkoch19! Which widget are you referencing?

**Comment by rkoch19** [comment]
Hello...Find coordinate....

2016-04-06 16:34 GMT-03:00 Brian Bunker <notifications@github.com>:

> Hi @rkoch19 <https://github.com/rkoch19>! Which widget are you
> referencing?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/BrianBunker/cmv-widgets/issues/20#issuecomment-206525527>
>



-- 
Renato Koch Murakami

**Comment by BrianBunker** [comment]
I'm not sure I understand...the widget doesn't show a graphic currently, so how are you placing pins on the map?

**Comment by rkoch19** [comment]
Whithin the Geocoder is possible?

2016-04-06 16:56 GMT-03:00 Brian Bunker <notifications@github.com>:

> I'm not sure I understand...the widget doesn't show a graphic currently,
> so how are you placing pins on the map?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/BrianBunker/cmv-widgets/issues/20#issuecomment-206532701>
>



-- 
Renato Koch Murakami

**Comment by BrianBunker** [comment]
I am sorry, the current widget only pans to a coordinate. I don't have any plans to start placing graphics with this widget or to persist points between page refreshes.
