### ISSUE TITLE
Adding shape files

### ISSUE THREAD

**Issue by deepal13** [BrianBunker/cmv-widgets#30]
Hi,

I tried adding the shape files you have provided but it doesn't seem to work. Can you please check?

Thanks

**Comment by BrianBunker** [comment]
@deepal13 Thanks for your interest in the DnD widget. I successfully downloaded the [sample shapefiles](https://github.com/BrianBunker/cmv-widgets/tree/master/DnD/sampledata) and dragged-and-dropped them onto [the sample application](http://brianbunker.github.io/dojo-esri-dnd-widget/).

**Comment by deepal13** [comment]
Hi Brian,

Thank you for your prompt response.

Yes, it is working in the sample application you just sent but it is not working in http://brianbunker.github.io/cmv-widgets/.

I downloaded the project from GitHub and it doesn't seem to work there as well.

Thanks

**Comment by BrianBunker** [comment]
Reopening due to to confirmed deficiency. Thanks for the clarification!

**Comment by deepal13** [comment]
Hi Brian, I copied the scripts from https://github.com/BrianBunker/dojo-esri-dnd-widget for DnD part and everything works fine now.

Thanks.

**Comment by BrianBunker** [comment]
Good to hear. I'm keeping this issue open so I can remember to get it working in this repo too.

**Comment by irisevenstar** [comment]
deepal13 - do you have something that is working for both shapefiles and kml, or just shapefiles? The code in the repo you pointed to appears to just work with shapefiles.

**Comment by tmcgee** [comment]
@irisevenstar The code in this cmv-widgets repo supports both shapefiles and kml. I am the one that added kml support. no support for kmz files currently.

**Comment by irisevenstar** [comment]
@tmcgee - I guess my question was whether what @deepal13 downloaded supported kml, since the shapefile functionality in this repo isn't working at the present time.

**Comment by tmcgee** [comment]
@irisevenstar I'm pretty sure that the comment related to the demo application here: http://brianbunker.github.io/cmv-widgets/. The code in this repo does work, just not in that demo.

**Comment by irisevenstar** [comment]
I don't think the shapefile code works, either in the repo or the demo. I'm experiencing the same issue in my own application using the repo code as is present in the demo where the shapefile doesn't appear on the map despite being zoomed to the area and showing up in the table of contents for the DnD widget.

**Comment by tmcgee** [comment]
@irisevenstar I see what you mean. Sorry, I misinterpreted the prior discussion. I am working on a Pull Request to fix this.

**Comment by irisevenstar** [comment]
@tmcgee Thank you. Everything appears to be working perfectly now.
