### ISSUE TITLE
Dnd Widget import

### ISSUE THREAD

**Issue by Samaalir** [BrianBunker/cmv-widgets#48]
Hello, can I Import A geo-referenced image (tif) with this plugin ? if not is there a possibility to do it ?

**Comment by BrianBunker** [comment]
Please see https://github.com/BrianBunker/cmv-widgets/issues/8.

**Comment by Samaalir** [comment]
So there is no functionality to import a geo-referenced image

**Comment by BrianBunker** [comment]
@Samaalir That is correct. It is possible to import the geotagged image, but I do not have the time to develop it now. I am open to accepting Pull Requests to add functionality.

Closing this issue because it duplicates #8.

**Comment by Samaalir** [comment]
I am developing it, thank you for your time
