### ISSUE TITLE
updateLocationHash triggers map.centerAndZoom

### ISSUE THREAD

**Issue by roemhildtg** [BrianBunker/cmv-widgets#7]
First, nice widget, This is really useful! 

One small issue me is after the map is panned or zoomed, it loads as expected, but then it adjusts a few pixels and reloads again. I'm not 100% sure if this is the issue, but what appears to be happening is when [hash](https://github.com/BrianBunker/cmv-widgets/blob/master/MapNavigationHash/MapNavigationHash.js#L53) is called hashUpdating seems to get set to false before the hash changes.

So what ends up happening is:
1. User pans map
2. Map reloads
3. Hash changes
3. Map centers and zooms onHashChange
4. Map reloads again

I'm not positive on this but maybe the hash function in [dojo/hash](https://github.com/dojo/dojo/blob/395cbc1cf9f4e72303268add46570aa52f0009d4/hash.js) is async and [this.hashUpdating](https://github.com/BrianBunker/cmv-widgets/blob/master/MapNavigationHash/MapNavigationHash.js#L54) gets set to false too quickly?

**Comment by BrianBunker** [comment]
Looking at dojo/hash, it doesn't appear to be async. I think the adjustment of a few pixels might be coming from rounding of the centerpoint coordinates. What do you think?
