### ISSUE TITLE
Generate Operation

### ISSUE THREAD

**Issue by faridcher** [BrianBunker/cmv-widgets#9]
Does the Generate operation (to create feature collection from csv file,...) work with ArcGis server Installation? Or it needs portal for ArcGis?
I need to replace [sample link!](http://www.arcgis.com/sharing/rest/content/features/generate) with my Local server.
Thanks

**Comment by BrianBunker** [comment]
It could work with ArcGIS Server, but you'll need to write a Geoprocessing script to convert the tabular data to features.
Another possibility is updating the widget code to do the table to feature conversion in the front-end. The current drag and drop [CSV example](https://developers.arcgis.com/javascript/jssamples/exp_dragdrop.html) on the JSAPI example site uses this workflow.
